### ISSUE TITLE
TODO: Add multipart body parser for HttpServer.

### ISSUE THREAD

**Issue by slaff** [slaff/Sming#22]
In order to be able to upload firmware or other content via HTTP server in Sming we need to have support for `multipart/form-data`.  For that we will need:
- [x] Streamable and interruptible `multipart/form-data` body parser
- [ ] A way to map form fields to streams - On a non-embedded device a POST data can be stored on a temporary location on the hard disk or in memory. On a embedded device as a microcontroller, for example, we don't have that luxury. Therefore we should have a way to define a mapping that takes care to save the incoming data directly to the designated location and also check the allowed length of that data. For example a form that uploads a firmware and a SpifFS data can have the following mapping:
```
{
    "firmware": rBootItemOutputStream(settings...),
   "spiffs" : rBootItemOutputStream(settings),
   "description": LimitedMemoryStream(1024),
    //...
}
```
Fields that are not mapped should be discarded. 
- [ ] The mapped form field streams should be available after the complete request is processed as request.postParams. For example `request.postParams["firmware"]` will provide access to the saved firmware.
- [ ] HttpServerOta sample should be provided with demonstration of upload via POST request, saving of the data and switching the active rom.

Initial work: Initial work has started at: https://github.com/slaff/Sming/tree/feature/httpserver-multipart-bodyparser
