### ISSUE TITLE
TODO: SSL abstraction.

### ISSUE THREAD

**Issue by slaff** [slaff/Sming#39]
The SSL abstraction should allow implementations based on axTLS, mbed-tls, bearSsl and others.

Initial work is done in https://github.com/slaff/Sming/tree/feature/ssl-abstraction. 

Tasks
- [x] Initial abstraction and implementation with axTLS and BearSSL
- [x] Apply coding style rules also to the SSL code
- [x] Document the interface classes
- [x] Update the Sphinx documentation.

**Comment by mikee47** [comment]
For info, have revisions for BR X509 certificate handling, debug messages, couple of other minor bits probably push them later today.

**Comment by kpishere** [comment]
Summary: Context, challenge, next steps?

CONTEXT:

@mikee47 @slaff May I say that you guys are doing some fantastic work here!  In my time on this little project with this framework, it went from un-workable to snappy with SSL client, some web hosting. I think also, you're surely aware, if this can get working nicely, this framework moves from home hobbyist stuff to corporate-ready.  As, in my case, I'd like to bring my IoT device into the office but there is no way this can happen unless it meets security standards in the office.

In this case, for a simple task of having ESP8266 connect to a user's outlook calendar, take today's events and show only the next event's location (where you got to be and when) you need to host an HTTPS web service, use mDNS, make HTTPS client connections, have NTTP client, and make a User authenticated OAuth2 authorization and token request with these tools .  You can skirt around the HTTPS web service a little but then the experience isn't 'clean'.

If this task is even achievable, I'd certainly be happy to share this service as a sample app in this repository when ready as it is would serve a good integrated example that is basis for other utilities.

CHALLANGE:

So, it will now go though login/authorization and get a token.  But, the device must be restarted after it gets the login page.  After getting the login page, the CODE is returned and saved.  Device must be restarted after that too.  From there, one can request a token.  To see the token in the browser, one must sometimes restart the device again to download the token.

After each step, serial output often shows : 

connected with 21Birc, channel 11
dhcp client start...
ip:192.168.2.2,mask:255.255.255.0,gw:192.168.2.1
New CPU frequency is:160

=== WEB SERVER STARTED ===
192.168.2.2
==============================

host_name = vfdkp
server_name = _vfdkp._tcp.local
pm open,type:2 0
{
  "tennentid": "XXX",
  "client_id": "XXX"
}86716048 

CONNECTION DROPPED
	(free heap: 15520)


86764142 

CONNECTION DROPPED
	(free heap: 15520)


86770013 

CONNECTION DROPPED
	(free heap: 15520)
 
NEXT STEPS:

How do you guys think I should proceed with this?  Attach debugger to device?  Get it running on my computer in hosted way and do memory leak analysis?  Can I do memory analysis remotely with the device and debugger?

I haven't tried attaching debugger or running in hosted mode yet.  Something to focus on and learn.

**Comment by mikee47** [comment]
@kpishere Sounds like an interesting project! I would certainly start by getting it running under under the Host environment. You will need to ensure any ESP-specific code is isolated at the source/module/library level. If you would like assistance with any of this then you might consider pushing your project to a public repo. so it can be discussed more easily.

I would suggest building Sming at `DEBUG_VERBOSE_LEVEL=3` so you can get a better picture of (a) how many connections are getting created, (b) how much RAM is getting consumed. All this high-level stuff is exactly why we have the Host builds: easier debugging, more available RAM, etc. You can enable additional memory tracking by including `<malloc_count.h>` and using methods in `MallocCount` namespace.

Assuming you're using 16K blocks, that means you're generally going to be restricted to a single client connection. The the `CONNECTION DROPPED` message tells you free heap has dropped below 16K, so either you're trying to create multiple client connections or the RAM is being consumed elsewhere.
