### ISSUE TITLE
TODO: Unify HTTP body processing

### ISSUE THREAD

**Issue by slaff** [slaff/Sming#50]
- [ ] Make HttpRequest and HttpResponse to inherit from HttpMessage (http://www.ietf.org/rfc/rfc7230.txt )
- [ ] Change the bodyParser callbacks to have the following signature
size_t formParser(HttpMessage& message, const char* at, int length)`
- [ ] Allow body parsers to be used also on the client side:
```
client.setBodyParser(<mime-type>, bodyParserCallback);
// Similar to
server.setBodyParser(<mime-type>, bodyParserCallback);
```
-  Make HttpClientConnection::onBody method to look simiar to HttpServerConnection::onBody
  - [ ] remove the response stream and replace it with bodyParser
  - [ ] move the `incomingRequest->requestBodyDelegate` after the body parser code.
