### ISSUE TITLE
Support for ESP32 architecture.

### ISSUE THREAD

**Issue by slaff** [slaff/Sming#57]
The following branch [feature/arch-esp32](https://github.com/slaff/Sming/tree/feature/arch-esp32) is used to add ESP32 architecture support to Sming. This ticket is created to collect all tasks needed to complete the support.

# Tasks
- [x] LWIP raw support
- [x] Spiffs Support
- [ ] Peripherals - at the moment only basic GPIO pinMode, digitalWrite and digitalRead + ADC analogRead are supported.
- [ ] WIFI WPS
- [x] WIFI SmartConfig
- [x] WIFI Station
- [x] WIFI AccessPoint
- [x] UART (needs a bit of polishing)
- [x] Hardware Timers

# Getting Started:
Here are the steps that can help you test it.
```
# get the ESP32 branch version
cd /tmp
git -b feature/arch-esp32 checkout https://github.com/slaff/Sming.git
cd Sming
export SMING_HOME=$(pwd)/Sming

# now make sure to install ESP-IDF version 4.0
# Follow the instructions from here: 
# https://github.com/slaff/Sming/blob/feature/arch-
esp32/Sming/Arch/Esp32/README.rst#requirements

# once you have ESP-IDF v4.0 try to compile the Basic_Blink sample.
cd $SMING_HOME/../samples/Basic_Blink
make SMING_ARCH=Esp32

# once the compilation finishes you can flash the application to a device using
# the standard command

make flash
```

# Troubleshooting:

## Backtrace Decoding:

When an application crashes on ESP32 a backtrace will be printed in the console. Only the backtrace part has to be copied and then you can execute the command below and paste the backtrace in the console:

```
python $SMING_HOME/Arch/Esp32/Tools/decode-stacktrace.py out/Esp32/debug/build/app.out
``` 

Example backtrace looks like:
```
0x400841c5:0x3ffb50e0 0x40084545:0x3ffb5100 0x400d291b:0x3ffb5120 0x4008238f:0x3ffb5150 0x40089d8d:0x3ffb5170 0x400e5f5d:0x3ffb5190 0x400e5ccd:0x3ffb51b0 0x400e5ca0:0x3ffb51d0 0x400e59fc:0x3ffb51f0 0x400e5bc1:0x3ffb5210 0x400e4658:0x3ffb5250 0x400e1a5f:0x3ffb5290 0x400e1a1e:0x3ffb52b0 0x400d0cc2:0x3ffb52d0 0x40087e09:0x3ffb52f0
```

**Comment by mikee47** [comment]
I note that this UART implementation uses FreeRTOS, but does it need to be thread-aware? Both UART and I2S hardware are very similar to the ESP8266, so my preference would be to port the existing 'Sming' drivers directly and avoid the additional overheads. Any thoughts?

**Comment by slaff** [comment]
> so my preference would be to port the existing 'Sming' drivers

I did it this way because I wanted to have UART working before I can go forward. I would love to avoid additional overhead so my suggestion would be to estimate the effort. And work on it, if it is doable, and does not interfere/conflict with other important ESP-IDF libraries like the WIFI one. Or the different loggers.

**Comment by mikee47** [comment]
I'll take a look at it.
