### ISSUE TITLE
TODO: Advanced samples

### ISSUE THREAD

**Issue by slaff** [slaff/Sming#9]
It would be great to have a sample that is demonstrating:
- [x] doing OTA over MQTT with SSL
- [ ] PhotoStream allowing to see live via web-browser what a camera is capturing
- [x] SSL based on BearSSL that supports:
     - sending of big handshakes (with big certificate chains)
     - real stream support
     - Forward Secrecy
